sudo: false

language: python

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  global:
    - secure: "ddpJ80hapY19xudhnHECEVbbfM+nc9UROV8nBgTdQmM9jRH8OD+29U0i0af4/Zz+9IJ2pffY5sPkUHQIQyNcnMp0xZM8ErAwcrhknnVFzjcHcuhSzfstB3l13D9qHPuD3/IdpnRRCDUwZ0a7IJwsrbk4n9CmAEV3PwNkRz3nlOo="
  matrix:
    - DJANGO=2.0
    - DJANGO=1.8.18
    - DJANGO=1.10.7
    - DJANGO=1.11

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO=2.0
    - python: "3.3"
      env: DJANGO=1.10.7
    - python: "3.3"
      env: DJANGO=1.11
    - python: "3.3"
      env: DJANGO=2.0
    - python: "3.6"
      env: DJANGO=1.8.18
    - python: "3.6"
      env: DJANGO=1.10.7

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - py.test -v --pep8 --cov-report xml --cov=django_bootstrap_breadcrumbs

after_success:
  - python-codacy-coverage -r coverage.xml

deploy:
  provider: pypi
  user: prymitive
  password:
    secure: AG4XNHGS0WlieYF+QviYA0k/Q9cLQQl2m53rKu3YjTE4r9uKR6ffAphm7fTNu7YS5dvfDIAGIrX60wM4Z9gm1mOWEBY8/LAjLDsCEN4myoUgVZXLtrEmzUUvyph8hBHw4OKJX17i36HUTFdEKrkWRti/zumpQoDcFhr1D8m37f4=
  on:
    tags: true
  distributions: sdist bdist_wheel
