language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=">=1.4,<1.5"
  - DJANGO=">=1.5,<1.6"
  - DJANGO=">=1.6,<1.7"

install:
  - pip install -U Django=="$DJANGO" --use-mirrors
  - pip install -Ur requirements-test.txt --use-mirrors

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls
