language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=1.3.7
  - DJANGO=1.4.10
  - DJANGO=1.5.5
  - DJANGO=1.6.2

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.3.7
    - python: "3.3"
      env: DJANGO=1.3.7
    - python: "3.2"
      env: DJANGO=1.4.10
    - python: "3.3"
      env: DJANGO=1.4.10

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls
