language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

env:
  - DJANGO=1.4.12
  - DJANGO=1.5.7
  - DJANGO=1.6.4

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=1.4.12
    - python: "3.3"
      env: DJANGO=1.4.12
    - python: "3.4"
      env: DJANGO=1.4.12

install:
  - pip install -U Django==$DJANGO
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -v --pep8

after_success:
  - coverage report -m
  - coveralls
